name: Java-SDK GitHub Actions
on:
  pull_request:
  release:
    types: [published, created, edited]
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build-ubuntu18:
    name: build-ubuntu18.04
    runs-on: ubuntu-18.04
    container:
      image: docker.io/ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install Ubuntu dependencies
        run: apt update && apt install -y git curl libssl-dev default-jdk build-essential
      - name: run integration testing
        run: /bin/bash .ci/ci_check.sh
  build-macos:
    name: build-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install openssl@1.1 openjdk
      - name: run integration testing
        run: /bin/bash .ci/ci_check.sh
  build-ubuntu20:
    name: build-ubuntu20.04
    runs-on: ubuntu-20.04
    container:
      image: docker.io/ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install Ubuntu dependencies
        run: ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && apt update && apt install -y git curl libssl-dev default-jdk build-essential
      - name: run integration testing
        run: /bin/bash .ci/ci_check.sh